name: release

on:
  push:
    tags: 
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.host }}

    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            gstreamer-arch: x86_64
            host: windows-latest
            archive: windows_x86_64
            exe: sphere-audio-visualizer-desktop.exe 
            itch-channel: windows
          - target: x86_64-unknown-linux-gnu
            gstreamer-arch: amd64
            host: ubuntu-latest
            archive: linux_x86_64
            exe: sphere-audio-visualizer-desktop
            itch-channel: linux
          - target: x86_64-apple-darwin
            gstreamer-arch: universal
            host: macos-latest
            archive: macos_x86_64
            exe: sphere-audio-visualizer-desktop
            itch-channel: mac

    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Install GStreamer
        uses: MrInformatic/install-gstreamer-action@v1.0.0
        with:
          arch: ${{ matrix.gstreamer-arch }}
          version: "1.22.0"
  
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup/toolchains/
            target
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose --target ${{ matrix.target }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --verbose --target ${{ matrix.target }}
        if: runner.os != 'macOS'
      
      - name: Package
        run: | 
          mkdir ${{ matrix.archive }}
          cp target/${{ matrix.target }}/release/${{ matrix.exe }} ${{ matrix.archive }}/
          cp README.md ${{ matrix.archive }}/
          cp LICENSE.md ${{ matrix.archive }}/
          cp settings.yaml ${{ matrix.archive }}/

      - uses: vimtor/action-zip@v1
        with:
          files: ${{ matrix.archive }}/
          dest: ${{ matrix.archive }}.zip
      
      - name: Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ matrix.archive }}.zip
          tags: true
          draft: true
          overwrite: true
        
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.itch-channel }}
          ITCH_GAME: sphere-audio-visualizer
          ITCH_USER: mrinformatic
          PACKAGE: ${{ matrix.archive }}
          VERSION: ${{ github.ref_name }}