name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install GStreamer
        uses: MrInformatic/install-gstreamer-action@v1.0.0
        with:
          arch: amd64
          version: "1.22.0"
      
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose
      
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --verbose
